### ISSUE TITLE
При переключении на другой стоп-кадр просит сохранить изменения хотя они не проводились

### ISSUE THREAD

**Issue by VesninEN** [JewishCoder/Cshapr#5]
Если щелкнуть по уже размеченному изображению и потом щелкнуть по другому изображению возникает диалог "Данные не сохранены. Сохранить?" хотя никакие данные не менялись. Этот диалог нужно выводить лишь тогда, когда произведены какие-либо изменения.

![2017-06-30_22-42-54](https://user-images.githubusercontent.com/29756588/27751553-8d7b8d74-5de5-11e7-8237-7c09da58ed4c.png)

**Comment by JewishCoder** [comment]
исправлено
