### ISSUE TITLE
Переход между стоп-кадрами одиночным кликом

### ISSUE THREAD

**Issue by VesninEN** [JewishCoder/Cshapr#6]
Сейчас для того чтобы перейти к другому стоп-кадру нужно дважды щелкнуть по имени файла, что неудобно. Нужно реализовать переход по одиночному клику. Это ускорит разметку. Также можно реализовать переход между стоп-кадрами кнопками "<", ">" на форме и с клавиатуры, например PageUp, PageDown.
Также можно вместо кнопки сохранить (или дополнительно) сделать кнопки "сохранить и вперед", "сохранить и назад", которые сразу сохраняют данные и переходят к следующему/предыдущему изображению.

**Comment by JewishCoder** [comment]
сделан переход по PageUp, PageDown и кнопки "Сохранить и вперед", "Сохранить и назад"
